// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250429093712_finald")]
    partial class finald
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.CropDiseasesEntity", b =>
                {
                    b.Property<int>("crop_id")
                        .HasColumnType("integer");

                    b.Property<int>("disease_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("updatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("crop_id", "disease_id");

                    b.HasIndex("disease_id");

                    b.ToTable("cropDiseasesEntities");
                });

            modelBuilder.Entity("WebApplication1.Models.CropDisorderEntity", b =>
                {
                    b.Property<int>("crop_id")
                        .HasColumnType("integer");

                    b.Property<int>("disorder_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("updatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("crop_id", "disorder_id");

                    b.HasIndex("disorder_id");

                    b.ToTable("cropDisorderEntities");
                });

            modelBuilder.Entity("WebApplication1.Models.CropEntity", b =>
                {
                    b.Property<int>("crop_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("crop_id"));

                    b.Property<DateTime>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("qrcodeTree")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("crop_id");

                    b.ToTable("cropsEntity");
                });

            modelBuilder.Entity("WebApplication1.Models.CropPestsEntity", b =>
                {
                    b.Property<int>("crop_id")
                        .HasColumnType("integer");

                    b.Property<int>("pest_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("crop_id1")
                        .HasColumnType("integer");

                    b.Property<int?>("pest_id1")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("crop_id", "pest_id");

                    b.HasIndex("crop_id1");

                    b.HasIndex("pest_id1");

                    b.ToTable("cropPestsEntity");
                });

            modelBuilder.Entity("WebApplication1.Models.DiseasesEntity", b =>
                {
                    b.Property<int>("disease_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("disease_id"));

                    b.Property<DateTime>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("disease_id");

                    b.ToTable("diseasesEntities");
                });

            modelBuilder.Entity("WebApplication1.Models.ExpertEntity", b =>
                {
                    b.Property<int>("expert_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("expert_id"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("specialization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("expert_id");

                    b.ToTable("expertEntity");
                });

            modelBuilder.Entity("WebApplication1.Models.ObservationDiseaseEntity", b =>
                {
                    b.Property<int>("observation_id")
                        .HasColumnType("integer");

                    b.Property<int>("disease_id")
                        .HasColumnType("integer");

                    b.Property<int?>("Observationdisease_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("observation_id1")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("observation_id", "disease_id");

                    b.HasIndex("disease_id");

                    b.HasIndex("observation_id1", "Observationdisease_id");

                    b.ToTable("observationDiseaseEntity");
                });

            modelBuilder.Entity("WebApplication1.Models.ObservationDisorderEntity", b =>
                {
                    b.Property<int>("observation_id")
                        .HasColumnType("integer");

                    b.Property<int>("disorder_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("disorder_id1")
                        .HasColumnType("integer");

                    b.Property<int?>("observation_id1")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("observation_id", "disorder_id");

                    b.HasIndex("disorder_id1");

                    b.HasIndex("observation_id1");

                    b.ToTable("observationDisorderEntity");
                });

            modelBuilder.Entity("WebApplication1.Models.ObservationEntity", b =>
                {
                    b.Property<int>("observation_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("observation_id"));

                    b.Property<DateTime>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("crop_id")
                        .HasColumnType("integer");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("observedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("rootstock_id")
                        .HasColumnType("integer");

                    b.Property<int>("stage_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("variety_id")
                        .HasColumnType("integer");

                    b.HasKey("observation_id");

                    b.ToTable("observationEntity");
                });

            modelBuilder.Entity("WebApplication1.Models.ObservationPestEntity", b =>
                {
                    b.Property<int>("observation_id")
                        .HasColumnType("integer");

                    b.Property<int>("pest_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("observation_id1")
                        .HasColumnType("integer");

                    b.Property<int?>("pest_id1")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("observation_id", "pest_id");

                    b.HasIndex("observation_id1");

                    b.HasIndex("pest_id1");

                    b.ToTable("observationPestEntity");
                });

            modelBuilder.Entity("WebApplication1.Models.PestsEntity", b =>
                {
                    b.Property<int>("pest_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("pest_id"));

                    b.Property<DateTime>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("pest_id");

                    b.ToTable("pestsEntity");
                });

            modelBuilder.Entity("WebApplication1.Models.PhenologicalStagesEntity", b =>
                {
                    b.Property<int>("stage_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("stage_id"));

                    b.Property<DateTime>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("crop_id")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("group_number")
                        .HasColumnType("integer");

                    b.Property<string>("stage_code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("stage_id");

                    b.ToTable("PhenologicalStagesEntity");
                });

            modelBuilder.Entity("WebApplication1.Models.PhysiologicalDisorderEntity", b =>
                {
                    b.Property<int>("disorder_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("disorder_id"));

                    b.Property<DateTime>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("disorder_id");

                    b.ToTable("PhysiologicalDisorderEntity");
                });

            modelBuilder.Entity("WebApplication1.Models.RootstocksEntity", b =>
                {
                    b.Property<int>("rootstock_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("rootstock_id"));

                    b.Property<DateTime>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("crop_id")
                        .HasColumnType("integer");

                    b.Property<int?>("crop_id1")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("rootstock_id");

                    b.HasIndex("crop_id1");

                    b.ToTable("rootstocksEntity");
                });

            modelBuilder.Entity("WebApplication1.Models.TreesTable", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("agroClimaticZone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("coloum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("crop_id")
                        .HasColumnType("integer");

                    b.Property<int>("expert_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("graftingAge")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("latitude")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("longitude")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("plantAge")
                        .HasColumnType("integer");

                    b.Property<string>("plantStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("rootstock_id")
                        .HasColumnType("integer");

                    b.Property<string>("row")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("variety_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("crop_id");

                    b.HasIndex("expert_id");

                    b.HasIndex("rootstock_id");

                    b.HasIndex("variety_id");

                    b.ToTable("treesTables");
                });

            modelBuilder.Entity("WebApplication1.Models.VarietiesEntity", b =>
                {
                    b.Property<int>("variety_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("variety_id"));

                    b.Property<DateTime>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("crop_id")
                        .HasColumnType("integer");

                    b.Property<int?>("crop_id1")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("variety_id");

                    b.HasIndex("crop_id1");

                    b.ToTable("varietiesEntity");
                });

            modelBuilder.Entity("WebApplication1.Models.CropDiseasesEntity", b =>
                {
                    b.HasOne("WebApplication1.Models.CropEntity", "Crop")
                        .WithMany()
                        .HasForeignKey("crop_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.DiseasesEntity", "Disease")
                        .WithMany()
                        .HasForeignKey("disease_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crop");

                    b.Navigation("Disease");
                });

            modelBuilder.Entity("WebApplication1.Models.CropDisorderEntity", b =>
                {
                    b.HasOne("WebApplication1.Models.CropEntity", "Crop")
                        .WithMany()
                        .HasForeignKey("crop_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.PhysiologicalDisorderEntity", "Disorder")
                        .WithMany()
                        .HasForeignKey("disorder_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crop");

                    b.Navigation("Disorder");
                });

            modelBuilder.Entity("WebApplication1.Models.CropPestsEntity", b =>
                {
                    b.HasOne("WebApplication1.Models.CropEntity", "Crop")
                        .WithMany()
                        .HasForeignKey("crop_id1");

                    b.HasOne("WebApplication1.Models.PestsEntity", "Pest")
                        .WithMany()
                        .HasForeignKey("pest_id1");

                    b.Navigation("Crop");

                    b.Navigation("Pest");
                });

            modelBuilder.Entity("WebApplication1.Models.ObservationDiseaseEntity", b =>
                {
                    b.HasOne("WebApplication1.Models.DiseasesEntity", "Disease")
                        .WithMany()
                        .HasForeignKey("disease_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.ObservationDiseaseEntity", "Observation")
                        .WithMany()
                        .HasForeignKey("observation_id1", "Observationdisease_id");

                    b.Navigation("Disease");

                    b.Navigation("Observation");
                });

            modelBuilder.Entity("WebApplication1.Models.ObservationDisorderEntity", b =>
                {
                    b.HasOne("WebApplication1.Models.PhysiologicalDisorderEntity", "Disorder")
                        .WithMany()
                        .HasForeignKey("disorder_id1");

                    b.HasOne("WebApplication1.Models.ObservationEntity", "Observation")
                        .WithMany()
                        .HasForeignKey("observation_id1");

                    b.Navigation("Disorder");

                    b.Navigation("Observation");
                });

            modelBuilder.Entity("WebApplication1.Models.ObservationPestEntity", b =>
                {
                    b.HasOne("WebApplication1.Models.ObservationEntity", "Observation")
                        .WithMany()
                        .HasForeignKey("observation_id1");

                    b.HasOne("WebApplication1.Models.PestsEntity", "Pest")
                        .WithMany()
                        .HasForeignKey("pest_id1");

                    b.Navigation("Observation");

                    b.Navigation("Pest");
                });

            modelBuilder.Entity("WebApplication1.Models.RootstocksEntity", b =>
                {
                    b.HasOne("WebApplication1.Models.CropEntity", "Crop")
                        .WithMany()
                        .HasForeignKey("crop_id1");

                    b.Navigation("Crop");
                });

            modelBuilder.Entity("WebApplication1.Models.TreesTable", b =>
                {
                    b.HasOne("WebApplication1.Models.CropEntity", "crop")
                        .WithMany()
                        .HasForeignKey("crop_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.ExpertEntity", "expert")
                        .WithMany()
                        .HasForeignKey("expert_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.RootstocksEntity", "rootstock")
                        .WithMany()
                        .HasForeignKey("rootstock_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.VarietiesEntity", "variety")
                        .WithMany()
                        .HasForeignKey("variety_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("crop");

                    b.Navigation("expert");

                    b.Navigation("rootstock");

                    b.Navigation("variety");
                });

            modelBuilder.Entity("WebApplication1.Models.VarietiesEntity", b =>
                {
                    b.HasOne("WebApplication1.Models.CropEntity", "Crop")
                        .WithMany()
                        .HasForeignKey("crop_id1");

                    b.Navigation("Crop");
                });
#pragma warning restore 612, 618
        }
    }
}
