// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250430154926_alldone")]
    partial class alldone
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.CropEntity", b =>
                {
                    b.Property<int>("crop_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("crop_id"));

                    b.Property<DateTime>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("qrcodeTree")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("crop_id");

                    b.ToTable("cropsEntity");
                });

            modelBuilder.Entity("WebApplication1.Models.DiseasesEntity", b =>
                {
                    b.Property<int>("disease_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("disease_id"));

                    b.Property<DateTime>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("disease_id");

                    b.ToTable("diseasesEntities");
                });

            modelBuilder.Entity("WebApplication1.Models.ExpertEntity", b =>
                {
                    b.Property<int>("expert_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("expert_id"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("specialization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("expert_id");

                    b.ToTable("expertEntity");
                });

            modelBuilder.Entity("WebApplication1.Models.HealthandDiseaseEntity", b =>
                {
                    b.Property<int>("healthandDiseaseEntity_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("healthandDiseaseEntity_Id"));

                    b.Property<string>("DamageReport")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Insects")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InsectsLevel")
                        .HasColumnType("integer");

                    b.Property<string>("NurientDefiency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ObservedDisease")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ObservedDiseaseLevel")
                        .HasColumnType("integer");

                    b.Property<string>("PhysiologicalDisorder")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PhysiologicalDisorderLevel")
                        .HasColumnType("integer");

                    b.HasKey("healthandDiseaseEntity_Id");

                    b.ToTable("healthandEntity");
                });

            modelBuilder.Entity("WebApplication1.Models.ManagementPraticesEntity", b =>
                {
                    b.Property<int>("managementPraticesEntity_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("managementPraticesEntity_Id"));

                    b.Property<string>("fertilizer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("fertilizerAmount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("fertilizerDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("micronutrients")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("micronutrientsAmount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("micronutrientsDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("weedControl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("weedControlAmount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("weedControlDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("managementPraticesEntity_Id");

                    b.ToTable("managementPraticesEntities");
                });

            modelBuilder.Entity("WebApplication1.Models.ObservationEntity", b =>
                {
                    b.Property<int>("observationEntity_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("observationEntity_Id"));

                    b.Property<int>("crop_id")
                        .HasColumnType("integer");

                    b.Property<int>("healthandDiseaseEntity_Id")
                        .HasColumnType("integer");

                    b.Property<int>("managementPraticesEntity_Id")
                        .HasColumnType("integer");

                    b.Property<int>("phenologicalEntity_Id")
                        .HasColumnType("integer");

                    b.Property<int>("yieldandProductivityEntity_Id")
                        .HasColumnType("integer");

                    b.HasKey("observationEntity_Id");

                    b.HasIndex("crop_id");

                    b.HasIndex("healthandDiseaseEntity_Id");

                    b.HasIndex("managementPraticesEntity_Id");

                    b.HasIndex("phenologicalEntity_Id");

                    b.HasIndex("yieldandProductivityEntity_Id");

                    b.ToTable("observationEntity");
                });

            modelBuilder.Entity("WebApplication1.Models.PhenologicalEntity", b =>
                {
                    b.Property<int>("PhenologicalEntity_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PhenologicalEntity_Id"));

                    b.Property<DateTime>("StageDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("blossomDensity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("growthScale")
                        .HasColumnType("integer");

                    b.Property<int>("phenologicalStageEntity_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PhenologicalEntity_Id");

                    b.HasIndex("phenologicalStageEntity_Id");

                    b.ToTable("PhenologicalEntity");
                });

            modelBuilder.Entity("WebApplication1.Models.PhenologicalStageEntity", b =>
                {
                    b.Property<int>("phenologicalStageEntity_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("phenologicalStageEntity_Id"));

                    b.Property<string>("stage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("phenologicalStageEntity_Id");

                    b.ToTable("phenlogicalStageEntities");
                });

            modelBuilder.Entity("WebApplication1.Models.RootstocksEntity", b =>
                {
                    b.Property<int>("rootstock_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("rootstock_id"));

                    b.Property<DateTime>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("rootstock_id");

                    b.ToTable("rootstocksEntity");
                });

            modelBuilder.Entity("WebApplication1.Models.TreesTable", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("agroClimaticZone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("coloum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("crop_id")
                        .HasColumnType("integer");

                    b.Property<int>("expert_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("graftingAge")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("latitude")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("longitude")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("plantAge")
                        .HasColumnType("integer");

                    b.Property<string>("plantStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("rootstock_id")
                        .HasColumnType("integer");

                    b.Property<string>("row")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("variety_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("crop_id");

                    b.HasIndex("expert_id");

                    b.HasIndex("rootstock_id");

                    b.HasIndex("variety_id");

                    b.ToTable("treesTables");
                });

            modelBuilder.Entity("WebApplication1.Models.VarietiesEntity", b =>
                {
                    b.Property<int>("variety_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("variety_id"));

                    b.Property<DateTime>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("variety_id");

                    b.ToTable("varietiesEntity");
                });

            modelBuilder.Entity("WebApplication1.Models.YieldandProductivityEntity", b =>
                {
                    b.Property<int>("yieldandProductivityEntity_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("yieldandProductivityEntity_Id"));

                    b.Property<int>("FruitQuality")
                        .HasColumnType("integer");

                    b.Property<int>("fruitSetPercent")
                        .HasColumnType("integer");

                    b.Property<DateTime>("harvestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("yieldAmount")
                        .HasColumnType("integer");

                    b.HasKey("yieldandProductivityEntity_Id");

                    b.ToTable("yieldandProductivityEntities");
                });

            modelBuilder.Entity("WebApplication1.Models.ObservationEntity", b =>
                {
                    b.HasOne("WebApplication1.Models.CropEntity", "crop")
                        .WithMany()
                        .HasForeignKey("crop_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.HealthandDiseaseEntity", "healthandDiseaseEntity")
                        .WithMany()
                        .HasForeignKey("healthandDiseaseEntity_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.ManagementPraticesEntity", "managementPraticesEntity")
                        .WithMany()
                        .HasForeignKey("managementPraticesEntity_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.PhenologicalEntity", "phenologicalEntity")
                        .WithMany()
                        .HasForeignKey("phenologicalEntity_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.YieldandProductivityEntity", "yieldandProductivityEntity")
                        .WithMany()
                        .HasForeignKey("yieldandProductivityEntity_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("crop");

                    b.Navigation("healthandDiseaseEntity");

                    b.Navigation("managementPraticesEntity");

                    b.Navigation("phenologicalEntity");

                    b.Navigation("yieldandProductivityEntity");
                });

            modelBuilder.Entity("WebApplication1.Models.PhenologicalEntity", b =>
                {
                    b.HasOne("WebApplication1.Models.PhenologicalStageEntity", "PhenlogicalStageEntity")
                        .WithMany()
                        .HasForeignKey("phenologicalStageEntity_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhenlogicalStageEntity");
                });

            modelBuilder.Entity("WebApplication1.Models.TreesTable", b =>
                {
                    b.HasOne("WebApplication1.Models.CropEntity", "crop")
                        .WithMany()
                        .HasForeignKey("crop_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.ExpertEntity", "expert")
                        .WithMany()
                        .HasForeignKey("expert_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.RootstocksEntity", "rootstock")
                        .WithMany()
                        .HasForeignKey("rootstock_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.VarietiesEntity", "variety")
                        .WithMany()
                        .HasForeignKey("variety_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("crop");

                    b.Navigation("expert");

                    b.Navigation("rootstock");

                    b.Navigation("variety");
                });
#pragma warning restore 612, 618
        }
    }
}
