// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250505073138_alldonesjsd")]
    partial class alldonesjsd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.CropEntity", b =>
                {
                    b.Property<int>("crop_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("crop_id"));

                    b.Property<DateTime>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("qrcodeTree")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("crop_id");

                    b.ToTable("cropsEntity");
                });

            modelBuilder.Entity("WebApplication1.Models.DiseasesEntity", b =>
                {
                    b.Property<int>("disease_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("disease_id"));

                    b.Property<DateTime>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<int>("level")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<DateTime>("updatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("disease_id");

                    b.ToTable("diseasesEntities");
                });

            modelBuilder.Entity("WebApplication1.Models.DisorderEntity", b =>
                {
                    b.Property<int>("disorder_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("disorder_id"));

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<int>("level")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.HasKey("disorder_id");

                    b.ToTable("DisorderEntity");
                });

            modelBuilder.Entity("WebApplication1.Models.ExpertEntity", b =>
                {
                    b.Property<int>("expert_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("expert_id"));

                    b.Property<string>("bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("year")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("expert_id");

                    b.ToTable("expertEntity");
                });

            modelBuilder.Entity("WebApplication1.Models.FertilizerEntity", b =>
                {
                    b.Property<int>("fertilizer_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("fertilizer_id"));

                    b.Property<int>("amountUsed")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<DateTime>("fertilizerDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.HasKey("fertilizer_id");

                    b.ToTable("FertilizerEntity");
                });

            modelBuilder.Entity("WebApplication1.Models.HealthandDiseaseEntity", b =>
                {
                    b.Property<int>("healthandDiseaseEntity_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("healthandDiseaseEntity_Id"));

                    b.Property<string>("DamageReport")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NurientDefiency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("disease_id")
                        .HasColumnType("integer");

                    b.Property<int>("disorder_id")
                        .HasColumnType("integer");

                    b.Property<int>("insect_id")
                        .HasColumnType("integer");

                    b.HasKey("healthandDiseaseEntity_Id");

                    b.HasIndex("disease_id");

                    b.HasIndex("disorder_id");

                    b.HasIndex("insect_id");

                    b.ToTable("healthandEntity");
                });

            modelBuilder.Entity("WebApplication1.Models.InsectsEntity", b =>
                {
                    b.Property<int>("insect_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("insect_id"));

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<int>("level")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.HasKey("insect_id");

                    b.ToTable("InsectsEntity");
                });

            modelBuilder.Entity("WebApplication1.Models.ManagementPraticesEntity", b =>
                {
                    b.Property<int>("managementPraticesEntity_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("managementPraticesEntity_Id"));

                    b.Property<int>("fertilizer_id")
                        .HasColumnType("integer");

                    b.Property<int>("micro_nutrient_id")
                        .HasColumnType("integer");

                    b.Property<int>("weed_control_id")
                        .HasColumnType("integer");

                    b.HasKey("managementPraticesEntity_Id");

                    b.HasIndex("fertilizer_id");

                    b.HasIndex("micro_nutrient_id");

                    b.HasIndex("weed_control_id");

                    b.ToTable("managementPraticesEntities");
                });

            modelBuilder.Entity("WebApplication1.Models.MicroNutrientsEntity", b =>
                {
                    b.Property<int>("micro_nutrient_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("micro_nutrient_id"));

                    b.Property<int>("amountUsed")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<DateTime>("microNutrientDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.HasKey("micro_nutrient_id");

                    b.ToTable("MicroNutrientsEntity");
                });

            modelBuilder.Entity("WebApplication1.Models.ObservationEntity", b =>
                {
                    b.Property<int>("observationEntity_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("observationEntity_Id"));

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<int>("crop_id")
                        .HasColumnType("integer");

                    b.Property<int>("healthandDiseaseEntity_Id")
                        .HasColumnType("integer");

                    b.Property<int>("managementPraticesEntity_Id")
                        .HasColumnType("integer");

                    b.Property<int>("phenologicalEntities_Id")
                        .HasColumnType("integer");

                    b.Property<int>("yieldandProductivityEntity_Id")
                        .HasColumnType("integer");

                    b.HasKey("observationEntity_Id");

                    b.HasIndex("crop_id");

                    b.HasIndex("healthandDiseaseEntity_Id");

                    b.HasIndex("managementPraticesEntity_Id");

                    b.HasIndex("phenologicalEntities_Id");

                    b.HasIndex("yieldandProductivityEntity_Id");

                    b.ToTable("observationEntity");
                });

            modelBuilder.Entity("WebApplication1.Models.PhenologicalEntities", b =>
                {
                    b.Property<int>("phenologicalEntities_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("phenologicalEntities_Id"));

                    b.Property<DateTime>("StageDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("blossomDensity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("growthScale")
                        .HasColumnType("integer");

                    b.Property<int>("phenologicalStageEntity_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("phenologicalEntities_Id");

                    b.HasIndex("phenologicalStageEntity_Id");

                    b.ToTable("phenologicalEntities");
                });

            modelBuilder.Entity("WebApplication1.Models.PhenologicalStageEntity", b =>
                {
                    b.Property<int>("phenologicalStageEntity_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("phenologicalStageEntity_Id"));

                    b.Property<string>("stageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("phenologicalStageEntity_Id");

                    b.ToTable("phenologicalStageEntity");
                });

            modelBuilder.Entity("WebApplication1.Models.RootstocksEntity", b =>
                {
                    b.Property<int>("rootstock_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("rootstock_id"));

                    b.Property<DateTime>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("rootstock_id");

                    b.ToTable("rootstocksEntity");
                });

            modelBuilder.Entity("WebApplication1.Models.TreesTable", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("agroClimaticZone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("coloum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("crop_id")
                        .HasColumnType("integer");

                    b.Property<int>("expert_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("graftingAge")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("latitude")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("longitude")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("plantAge")
                        .HasColumnType("integer");

                    b.Property<string>("plantStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("rootstock_id")
                        .HasColumnType("integer");

                    b.Property<string>("row")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("variety_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("crop_id");

                    b.HasIndex("expert_id");

                    b.HasIndex("rootstock_id");

                    b.HasIndex("variety_id");

                    b.ToTable("treesTables");
                });

            modelBuilder.Entity("WebApplication1.Models.VarietiesEntity", b =>
                {
                    b.Property<int>("variety_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("variety_id"));

                    b.Property<DateTime>("createdOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("variety_id");

                    b.ToTable("varietiesEntity");
                });

            modelBuilder.Entity("WebApplication1.Models.WeedControlEnity", b =>
                {
                    b.Property<int>("weed_control_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("weed_control_id"));

                    b.Property<int>("amountUsed")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<DateTime>("weedControlDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("weed_control_id");

                    b.ToTable("WeedControlEnity");
                });

            modelBuilder.Entity("WebApplication1.Models.YieldandProductivityEntity", b =>
                {
                    b.Property<int>("yieldandProductivityEntity_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("yieldandProductivityEntity_Id"));

                    b.Property<int>("FruitQuality")
                        .HasColumnType("integer");

                    b.Property<int>("fruitSetPercent")
                        .HasColumnType("integer");

                    b.Property<DateTime>("harvestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("yieldAmount")
                        .HasColumnType("integer");

                    b.HasKey("yieldandProductivityEntity_Id");

                    b.ToTable("yieldandProductivityEntities");
                });

            modelBuilder.Entity("WebApplication1.Models.HealthandDiseaseEntity", b =>
                {
                    b.HasOne("WebApplication1.Models.DiseasesEntity", "Diseases")
                        .WithMany()
                        .HasForeignKey("disease_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.DisorderEntity", "Disorder")
                        .WithMany()
                        .HasForeignKey("disorder_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.InsectsEntity", "Insects")
                        .WithMany()
                        .HasForeignKey("insect_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diseases");

                    b.Navigation("Disorder");

                    b.Navigation("Insects");
                });

            modelBuilder.Entity("WebApplication1.Models.ManagementPraticesEntity", b =>
                {
                    b.HasOne("WebApplication1.Models.FertilizerEntity", "Fertilizer")
                        .WithMany()
                        .HasForeignKey("fertilizer_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.MicroNutrientsEntity", "MicroNutrient")
                        .WithMany()
                        .HasForeignKey("micro_nutrient_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.WeedControlEnity", "WeedControl")
                        .WithMany()
                        .HasForeignKey("weed_control_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fertilizer");

                    b.Navigation("MicroNutrient");

                    b.Navigation("WeedControl");
                });

            modelBuilder.Entity("WebApplication1.Models.ObservationEntity", b =>
                {
                    b.HasOne("WebApplication1.Models.CropEntity", "crop")
                        .WithMany()
                        .HasForeignKey("crop_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.HealthandDiseaseEntity", "healthandDiseaseEntity")
                        .WithMany()
                        .HasForeignKey("healthandDiseaseEntity_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.ManagementPraticesEntity", "managementPraticesEntity")
                        .WithMany()
                        .HasForeignKey("managementPraticesEntity_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.PhenologicalEntities", "phenologicalEntities")
                        .WithMany()
                        .HasForeignKey("phenologicalEntities_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.YieldandProductivityEntity", "yieldandProductivityEntity")
                        .WithMany()
                        .HasForeignKey("yieldandProductivityEntity_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("crop");

                    b.Navigation("healthandDiseaseEntity");

                    b.Navigation("managementPraticesEntity");

                    b.Navigation("phenologicalEntities");

                    b.Navigation("yieldandProductivityEntity");
                });

            modelBuilder.Entity("WebApplication1.Models.PhenologicalEntities", b =>
                {
                    b.HasOne("WebApplication1.Models.PhenologicalStageEntity", "phenlogicalStageEntity")
                        .WithMany()
                        .HasForeignKey("phenologicalStageEntity_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("phenlogicalStageEntity");
                });

            modelBuilder.Entity("WebApplication1.Models.TreesTable", b =>
                {
                    b.HasOne("WebApplication1.Models.CropEntity", "crop")
                        .WithMany()
                        .HasForeignKey("crop_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.ExpertEntity", "expert")
                        .WithMany()
                        .HasForeignKey("expert_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.RootstocksEntity", "rootstock")
                        .WithMany()
                        .HasForeignKey("rootstock_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.VarietiesEntity", "variety")
                        .WithMany()
                        .HasForeignKey("variety_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("crop");

                    b.Navigation("expert");

                    b.Navigation("rootstock");

                    b.Navigation("variety");
                });
#pragma warning restore 612, 618
        }
    }
}
